name: build

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['22.2', '23.1']
        elixir: ['1.8.2', '1.9.4', '1.10.3']

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: 1.10.4
          otp-version: 23.1
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix credo --strict
